### ISSUE TITLE
implementation questions about the 'lars_simclr'

### ISSUE THREAD

**Issue by Adasunnylily** [GANPerf/LCR#4]
In the configs of the implementation of **byol** all of the **train.optimizer.name** is **'lars_simclr'**, however, in the  /LCR/optimizers/__init__.py, there exists noting about lars_simclr, only import lars and larc. Thus I am really confused about whether this is the full implementation code, is there any code left for implementation? 
looking forward to your reply.
thanks a lot!

**Comment by GANPerf** [comment]
> In the configs of the implementation of **byol** all of the **train.optimizer.name** is **'lars_simclr'**, however, in the /LCR/optimizers/**init**.py, there exists noting about lars_simclr, only import lars and larc. Thus I am really confused about whether this is the full implementation code, is there any code left for implementation? looking forward to your reply. thanks a lot!

Sorry about that. I delete the part of simclr and simsiam but not deleted so clear. Instead, we concentrate on applying our method to BYOL  and MoCo v2, as outlined in our paper. This adjustment allows us to showcase the effectiveness and performance of our approach specifically within the BYOL and MoCo v2 frameworks. . The simclr and simsiam is irrelevant.

**Comment by Adasunnylily** [comment]
Thank you for your answer, so is lars the optimizer used for BYOL and MoCo v2？

**Comment by GANPerf** [comment]
> Thank you for your answer, so is lars the optimizer used for BYOL and MoCo v2？

lars is only used for BYOL. For MoCo v2, SGD is used and I will release them in near future.
